### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by kraa965** [CaiVR/CaiVR-Custom-Haptic-Vest-V1#1]
Hi, I saw your homemade device for vr chat, I wanted to know at what stage of development to synchronize with bhaptic?

**Comment by CaiVR** [comment]
Hi, sorry this took a while for me to reply to. bHaptics interpretation is a planned feature, but other updates will have to be made to this project for that to be possible. I am currently working on a full overhaul of the PC client from just a script into a fully fledged piece of software with a suite of tools to configure and help make the experience of making and using a DIY vest much easier. If you want a DIY haptics alternative, try [Openhaptics](https://github.com/openhaptics/openhaptics-firmware). It's a recently revived project that is dedicated entirely to emulating bHaptics devices specifically. It lacks the potential flexibility of a fully open solution because it relies entirely on the bHaptics player, but it works very well.
Hope this helps!
